### ISSUE TITLE
header on event page not working

### ISSUE THREAD

**Issue by vinzenzweber** [bradphelan/openkitchen#15]
"Web I" becomes "Web i"
AND
that javascript "tab bar" has no items at all ... it's just a simple white thingy ...

**Comment by vinzenzweber** [comment]
by the way "Web I" aka "web one" is supposed to be the event name for my first OPENKITCHEN regarding the website ;)

**Comment by bradphelan** [comment]
Will add

```
text-transform: capitalize
```

to the css for that element
