### ISSUE TITLE
sending invitations not working

### ISSUE THREAD

**Issue by vinzenzweber** [bradphelan/openkitchen#16]
I am trying to invite people (well actually my email addresses and julia) but no emails are sent

**Comment by bradphelan** [comment]
Yeah, I had some threading issue todo with the email queue and the new process model I'm using. I actually fixed it and it is deploying right now.

Commit https://github.com/bradphelan/openkitchen/commit/545ba6a212daaffa0d547df5c24995a0781c9317

**Comment by bradphelan** [comment]
It's deployed now so give it a try.
