### ISSUE TITLE
clicking on a user opens mail

### ISSUE THREAD

**Issue by vinzenzweber** [bradphelan/openkitchen#17]
clicking on a user who is registered should open his profile page
this is an important social feature
I want to know more about the people I am going to meet at OPENKITCHEN
maybe we should'nt do any action with unregistered users (email address only) ??

**Comment by bradphelan** [comment]
I agree. However the permissions thing with the social profile gets tricky. Needs thinking and discussing. Who's profile can I see? Everybody, Those who I have been **invited by** or those who I have been **invited with**. Does just inviting somebody make it you can see thier profile.  Lots of headache for you to sleep on ;)

**Comment by bradphelan** [comment]
Emails are now no longer shown. If the name is not provided then I use the email address leader without the domain eg.

```
bradphelan@xtargets.com
```

is used as

```
bradphelan@....
```
