### ISSUE TITLE
Scenario: Commenting System for private events

### ISSUE THREAD

**Issue by vinzenzweber** [bradphelan/openkitchen#3]
Scenario: Commenting System for private events

As a host
When a comment is made on the event wall
Then I will receive an email notification

As an invited user who has not yet accepted
When a comment is made on the event wall
Then I will NOT receive an email notification

As an invited user who HAS accepted
When a comment is made on the event wall
Then I will receive an email notification

As an invited user who HAS NOT YET accepted and has made at least one comment on the event wall
When a comment by another user is made on the event wall
Then I will receive an email notification

Scenario: Commenting System for public events

As a registered user who is NOT invited
When I make a comment on the event wall
Then I will receive email notification for future comments

**Comment by bradphelan** [comment]
Fixed.... but public events need to be specced seperately
