### ISSUE TITLE
geolocation is requested on EACH page load

### ISSUE THREAD

**Issue by vinzenzweber** [bradphelan/openkitchen#30]

**Comment by bradphelan** [comment]
Something wrong with your browser perhaps. Once I give the browser permission then it never asks me again. What browser, version, platform is this problem on?

**Comment by vinzenzweber** [comment]
Firefox 10.0.2 on Mac OS X 10.8
and it is still bothering me .. :D

**Comment by bradphelan** [comment]
Yeah I managed to replicate the problem. Requires a bit of fix in my code
to cache results for a bit.
On Mar 20, 2012 4:05 PM, "Vinzenz-Emanuel Weber" <
reply@reply.github.com>
wrote:
